// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjybkapthvtuqvzlcybk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqeWJrYXB0aHZ0dXF2emxjeWJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDQxMTksImV4cCI6MjA2NjYyMDExOX0.yUMTcOIhRrEHd7ZWqyRDtZIpkbjy1P22MmCKsgI-wfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);